import CheckUser from '@/components/CheckUser';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Lexend, Poppins, Roboto } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});
const robotoFont = Roboto({
	variable: '--font-roboto',
	weight: ['400', '600', '800'],
	subsets: ['latin'],
});
const poppinsFont = Poppins({
	variable: '--font-poppins',
	weight: ['400', '600', '800'],
	subsets: ['latin'],
});
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};
export const lexendFont = Lexend({
	style: 'normal',
	weight: ['400', '700'],
	subsets: ['latin'],
	variable: '--font-lexend',
});
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${robotoFont.variable} ${poppinsFont.variable} ${lexendFont.variable} antialiased font-roboto`}
			>
				<div className=" w-full flex items-center justify-center ">
					{children}
				</div>
			</body>
		</html>
	);
}
